/**
 * Shared vocabulary for the token pipeline.
 *
 * THE MECHANICAL RULE, in code:
 *
 *   the CSS variable name is the Tailwind token path with dots as dashes
 *
 *   line.strong  <->  --line-strong
 *   ink.2        <->  --ink-2
 *   brand.500    <->  --brand-500
 *   cat.food-bg  <->  --cat-food-bg
 *
 * That is the entire naming policy, and the reason it is a policy at all is
 * that a script can check it. Before it, five sets broke it in both directions
 * at once — Tailwind key `line` with CSS var `--border`, Tailwind key `ink`
 * with CSS var `--text-primary` — so neither name could be trusted to find the
 * other, and a class copied from a wireframe into an app silently painted
 * nothing.
 */

/** `success-bg` -> ['success','bg'].  `success` -> ['success','DEFAULT']. */
export function splitKey(key) {
  const i = key.indexOf("-");
  if (i === -1) return [key, "DEFAULT"];
  return [key.slice(0, i), key.slice(i + 1)];
}

/** Flat canonical keys -> the nested object Tailwind's `colors` wants. */
export function nestColors(keys, valueFor) {
  const out = {};
  for (const key of keys) {
    const [group, leaf] = splitKey(key);
    (out[group] ??= {})[leaf] = valueFor(key);
  }
  // A group that only ever got DEFAULT is a flat colour, not a one-key object.
  for (const [group, leaves] of Object.entries(out)) {
    const names = Object.keys(leaves);
    if (names.length === 1 && names[0] === "DEFAULT") out[group] = leaves.DEFAULT;
  }
  return out;
}

/** Every colour key a palette declares, canon first then reserved. */
export function paletteKeys(palette) {
  const themes = Object.values(palette.themes ?? {});
  const canon = new Set();
  for (const theme of themes) for (const k of Object.keys(theme)) canon.add(k);
  const reserved = Object.keys(palette.reserved ?? {}).filter((k) => k !== "_");
  return { canon: [...canon], reserved };
}

/**
 * The value a theme gives a reserved key.
 *
 * Reserved entries are `{ light, dark }` rather than bare strings because a
 * reserved colour still has to survive a theme flip — aakalan's seven category
 * pairs all have dark values, and dropping them on the dark side is exactly
 * how a category plate ends up unreadable at night.
 */
export function reservedValue(entry, themeName) {
  if (entry == null) return null;
  if (typeof entry === "string") return entry;
  return entry[themeName] ?? entry.light ?? null;
}

/** JSON keys starting `_` are prose for humans. Never emit them. */
export function isNote(key) {
  return key === "_" || key.startsWith("_");
}

export function entries(obj) {
  return Object.entries(obj ?? {}).filter(([k]) => !isNote(k));
}

/** A generated file says so, in the comment syntax of its own language. */
export function banner(version, source, comment = "css") {
  const lines = [
    "GENERATED by scripts/build-tokens.mjs — DO NOT EDIT.",
    "",
    `design-system version: ${version}`,
    `source: design-system/${source}`,
    "",
    "Edit the source and regenerate. `node scripts/build-tokens.mjs --check`",
    "regenerates into a temp dir and diffs, so a hand edit here fails the build",
    "rather than surviving as a twelfth source of truth.",
  ];
  if (comment === "css") return `/*\n${lines.map((l) => ` * ${l}`.trimEnd()).join("\n")}\n */`;
  return lines.map((l) => `// ${l}`.trimEnd()).join("\n");
}

const IDENT = /^[A-Za-z_$][A-Za-z0-9_$]*$/;
const INLINE_WIDTH = 74;

/**
 * JS object literal, compact where it stays readable.
 *
 * JSON.stringify with an indent turns every fontSize tuple into eight lines,
 * which buries a 20-token scale in 200 lines of punctuation. A generated file
 * nobody can read at review is a generated file nobody reviews, so leaves that
 * fit on one line stay on one line.
 */
export function literal(value, indent = "") {
  const pad = indent + "  ";
  if (value === null || typeof value !== "object") return JSON.stringify(value);

  const flat = JSON.stringify(value);
  if (flat.length + indent.length <= INLINE_WIDTH) {
    return Array.isArray(value)
      ? `[${value.map((v) => literal(v)).join(", ")}]`
      : `{ ${Object.entries(value).map(([k, v]) => `${key(k)}: ${literal(v)}`).join(", ")} }`;
  }

  if (Array.isArray(value)) {
    return `[\n${value.map((v) => pad + literal(v, pad)).join(",\n")},\n${indent}]`;
  }
  const body = Object.entries(value)
    .map(([k, v]) => `${pad}${key(k)}: ${literal(v, pad)}`)
    .join(",\n");
  return `{\n${body},\n${indent}}`;
}

function key(k) {
  return IDENT.test(k) ? k : JSON.stringify(k);
}
