#!/usr/bin/env node
/**
 * Pull store assets out of the (private) app repos and write web-sized
 * derivatives into public/media/.
 *
 * WHY DERIVATIVES AND NOT THE ORIGINALS
 * Store screenshots are 1080×2400 and up because the stores demand it — the
 * five apps here hold ~42MB of PNG. The site displays them at ~210px wide.
 * Committing the originals would add 42MB to a repo whose entire history is
 * under 2MB, and git never forgets a blob. WebP at 640px wide lands at ~40-70KB,
 * which is ~20x smaller and indistinguishable at display size.
 *
 * WHY IT RUNS LOCALLY AND NOT IN CI
 * The app repos are private and live as siblings under ~/git. A GitHub Action
 * on this public repo cannot read them. So this runs on a machine that has the
 * whole tree, and the derivatives are committed. Same shape as ~/git/bin/index.
 *
 * WHAT IT WILL NOT DO
 * It never copies video. The two .mp4 files in the tree are 55MB between them
 * and would be unrecoverable once pushed.
 *
 *   node scripts/sync-assets.mjs
 */
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { mkdir, readdir, writeFile, rm, stat } from "node:fs/promises";
import { join, basename, extname } from "node:path";
import { homedir } from "node:os";

const run = promisify(execFile);
const APPS = join(homedir(), "git", "apps");
const OUT = join(process.cwd(), "public", "media");
const DATA = join(process.cwd(), "src", "data", "media.json");

const SHOT_WIDTH = 640;   // displayed ~210px; 640 covers 3x displays
const ICON_SIZE = 256;
const QUALITY = 78;

/** slug → app repo directory name. Only apps with a real store folder. */
const SOURCES = {
  charades: "charades",
  imposter: "imposter",
  aakalan: "aakalan",
  askcal: "askcal",
  "tic-tac-toe": "tic-tac-toe",
  chitragupt: "chitragupt",
};

const MAX_SHOTS = 4; // curated, not a dump — see /design/gallery

const exists = async (p) => { try { await stat(p); return true; } catch { return false; } };

async function toWebp(src, dest, width) {
  // sips resizes (built into macOS, no dependency); cwebp converts.
  const tmp = dest.replace(/\.webp$/, ".tmp.png");
  await run("sips", ["--resampleWidth", String(width), src, "--out", tmp]);
  await run("cwebp", ["-quiet", "-q", String(QUALITY), tmp, "-o", dest]);
  await rm(tmp, { force: true });
  return (await stat(dest)).size;
}

const manifest = {};
const skipped = [];
let bytes = 0, files = 0;

await rm(OUT, { recursive: true, force: true });

for (const [slug, dir] of Object.entries(SOURCES)) {
  const store = join(APPS, dir, ".context", "documents", "store");
  if (!(await exists(store))) { skipped.push({ slug, why: "no store folder in the app repo" }); continue; }

  const destDir = join(OUT, slug);
  const entry = { icon: null, shots: [] };

  const icon = join(store, "icon-512.png");
  if (await exists(icon)) {
    await mkdir(destDir, { recursive: true });
    const d = join(destDir, "icon.webp");
    bytes += await toWebp(icon, d, ICON_SIZE); files++;
    entry.icon = `/media/${slug}/icon.webp`;
  }

  const shotsDir = join(store, "screenshots");
  if (await exists(shotsDir)) {
    const pngs = (await readdir(shotsDir)).filter((f) => extname(f) === ".png").sort().slice(0, MAX_SHOTS);
    for (const f of pngs) {
      await mkdir(destDir, { recursive: true });
      const name = basename(f, ".png").replace(/^\d+[-_]?/, "") || basename(f, ".png");
      const d = join(destDir, `${name}.webp`);
      bytes += await toWebp(join(shotsDir, f), d, SHOT_WIDTH); files++;
      // The filename is the caption source — "01-setup.png" becomes "setup".
      entry.shots.push({ src: `/media/${slug}/${name}.webp`, label: name.replace(/[-_]/g, " ") });
    }
  }

  if (!entry.icon && entry.shots.length === 0) {
    skipped.push({ slug, why: "store folder exists but holds no icon-512.png or screenshots/" });
    continue;
  }
  manifest[slug] = entry;
}

await writeFile(
  DATA,
  JSON.stringify(
    {
      $comment:
        "GENERATED by scripts/sync-assets.mjs from the private app repos. Do not hand-edit. Apps absent from `media` have no store assets to derive from — the site renders a labelled placeholder for those, which is the point.",
      generatedOn: new Date().toISOString().slice(0, 10),
      media: manifest,
      missing: skipped,
    },
    null,
    2,
  ) + "\n",
);

console.log(`synced ${files} file(s), ${(bytes / 1024).toFixed(0)}KB total`);
for (const [slug, e] of Object.entries(manifest))
  console.log(`  ${slug.padEnd(18)} icon:${e.icon ? "yes" : " no"}  shots:${e.shots.length}`);
for (const s of skipped) console.log(`  ${s.slug.padEnd(18)} SKIPPED — ${s.why}`);
